version: "3"

services:
  db:
    image: postgres:12
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
#    command: ["postgres", "-c", "log_statement=all"]

  gateway:
    image: tmcgroul/archive-gateway:15
    depends_on:
      - db
    environment:
      DATABASE_TYPE: postgres
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: actix_web=info,actix_server=info
      EVM_SUPPORT: "true"
    ports:
      - "${GW_PORT}:8000"
